name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.14
        uses: actions/setup-node@v3
        with:
          node-version: "16.14"
          cache: "npm"
          cache-dependency-path: './server/package-lock.json'
      - run: npm install
      - run: npm test
